# Generated by Django 3.1 on 2020-08-28 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DB_Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wk_str', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DB_Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=200)),
                ('has_final', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='DB_Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_str', models.CharField(max_length=200)),
                ('learning_str', models.CharField(max_length=200)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.db_schedule')),
            ],
        ),
        migrations.AddField(
            model_name='db_schedule',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.db_unit'),
        ),
        migrations.CreateModel(
            name='DB_Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_str', models.CharField(max_length=200)),
                ('description_title', models.CharField(max_length=200)),
                ('description_body', models.CharField(max_length=200)),
                ('weight', models.CharField(max_length=200)),
                ('due_str', models.CharField(max_length=200)),
                ('due_date', models.CharField(max_length=200)),
                ('is_final', models.BooleanField()),
                ('length', models.CharField(max_length=200)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.db_unit')),
            ],
        ),
    ]
