# Generated by Django 3.1 on 2020-08-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_assessment',
            name='due_date',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='db_assessment',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='db_unit',
            name='has_final',
            field=models.BooleanField(default=False),
        ),
    ]
