# Generated by Django 3.1 on 2020-08-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_unit',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
