# Generated by Django 3.1 on 2020-08-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_auto_20200828_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_assessment',
            name='description_body',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
