# Generated by Django 3.1 on 2020-08-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_db_unit_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_assessment',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='db_schedule',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='db_topic',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
